spring.application.name=sql-playground


spring.datasource.url=jdbc:postgresql://localhost:5433/sqlplayground
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.datasource.driver-class-name=org.postgresql.Driver